name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: corepack enable

      - name: Setup Node.js
        uses: ./.github/workflows/setup-node
      
      - name: Cache node_modules
        uses: ./.github/workflows/cache-node-modules

      - run: npm install

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/workflows/setup-node

      - name: Cache node_modules
        uses: ./.github/workflows/cache-node-modules

      # install if cache is missing or failed
      - run: npm install

      - name: Create .env file
        run: |
          echo "NUXT_PUBLIC_MAPTILER_KEY=${{ secrets.NUXT_PUBLIC_MAPTILER_KEY }}" >> .env

      - name: Build the site
        run: NUXT_APP_BASE_URL=/velotaf/ npx nuxt build --preset github_pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
